[project]
name = "mangolint"
version = "0.1.0"
description = "Enrich your writing with Indigenous language words"
authors = [
    {name = "nicol"}
]
readme = "README.md"
requires-python = "^3.10"
dependencies = [
    "fastapi (>=0.129.0,<0.130.0)",
    "uvicorn (>=0.40.0,<0.41.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "python-dotenv (>=1.2.1,<2.0.0)"
]

[tool.poetry]
package-mode = false


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
